/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./assets/**/*.{vue,js,css}",
		"./components/**/*.{vue,js}",
		"./layOuts/**/*.vue",
		"./pages/**/*.vue",
		"./plugins/**/*.{js,ts}",
		"./nuxt.config.{js,ts}",
	],
	theme: {
		extend: {
			keyframes: {
				"fade-in": {
					"0%": { opacity: "0%" },
					"100%": { opacity: "100%" },
				},
			},
			animation: {
				"fade-in": "fade-in 0.5s ease-in-Out",
			},
			colors: {
				/* light */
				colorPrimaryLight: "#7a5900",
				colorOnPrimaryLight: "#ffffff",
				colorPrimaryContainerLight: "#ffdea3",
				colorOnPrimaryContainerLight: "#261900",
				colorSecondaryLight: "#765a00",
				colorOnSecondaryLight: "#ffffff",
				colorSecondaryContainerLight: "#ffdf96",
				colorOnSecondaryContainerLight: "#251a00",
				colorTertiaryLight: "#626200",
				colorOnTertiaryLight: "#ffffff",
				colorTertiaryContainerLight: "#eae867",
				colorOnTertiaryContainerLight: "#1d1d00",
				colorErrorLight: "#ba1a1a",
				colorErrorContainerLight: "#ffdad6",
				colorOnErrorLight: "#ffffff",
				colorOnErrorContainerLight: "#410002",
				colorBackgroundLight: "#fffbff",
				colorOnBackgroundLight: "#1e1b16",
				colorSurfaceLight: "#fffbff",
				colorOnSurfaceLight: "#1e1b16",
				colorSurfaceVariantLight: "#ede1cf",
				colorOnSurfaceVariantLight: "#4d4639",
				colorOutlineLight: "#847965",
				colorInverseOnSurfaceLight: "#f8efe7",
				colorInverseSurfaceLight: "#34302a",
				colorInversePrimaryLight: "#fabd2f",
				colorShadowLight: "#000000",
				colorSurfacetintLight: "#7a5900",
				colorOutlineVariantLight: "#d1c5b4",
				colorScrimLight: "#000000",
				/* dark */
				colorPrimaryDark: "#fabd2f",
				colorOnPrimaryDark: "#402d00",
				colorPrimaryContainerDark: "#5d4200",
				colorOnPrimaryContainerDark: "#ffdea3",
				colorSecondaryDark: "#f1c038",
				colorOnSecondaryDark: "#3e2e00",
				colorSecondaryContainerDark: "#5a4400",
				colorOnSecondaryContainerDark: "#ffdf96",
				colorTertiaryDark: "#cdcc4e",
				colorOnTertiaryDark: "#333200",
				colorTertiaryContainerDark: "#4a4900",
				colorOnTertiaryContainerDark: "#eae867",
				colorErrorDark: "#ffb4ab",
				colorErrorContainerDark: "#93000a",
				colorOnErrorDark: "#690005",
				colorOnErrorContainerDark: "#ffdad6",
				colorBackgroundDark: "#1e1b16",
				colorOnBackgroundDark: "#e9e1d9",
				colorSurfaceDark: "#1e1b16",
				colorOnSurfaceDark: "#e9e1d9",
				colorSurfaceVariantDark: "#4d4639",
				colorOnSurfaceVariantDark: "#d1c5b4",
				colorOutlineDark: "#33847965",
				colorInverseOnSurfaceDark: "#1e1b16",
				colorInverseSurfaceDark: "#e9e1d9",
				colorInversePrimaryDark: "#7a5900",
				colorShadowDark: "#000000",
				colorSurfacetintDark: "#fabd2f",
				colorOutlineVariantDark: "#4d4639",
				colorScrimDark: "#000000",
			},
		},
	},
}
